version: '2'
services:

  db:
    image: postgres:9.6
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=prod
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  web: &app
    build: .
    environment:
      - VIRTUAL_HOST=beer.docker
      - SECRET_KEY_BASE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - RAILS_ENV=production
    depends_on:
      - db
      - redis
      - cache

  worker:
    <<: *app
    command: bundle exec sidekiq -e production -c 25
    environment:
      - SECRET_KEY_BASE
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  proxy:
    image: jwilder/nginx-proxy:latest
    environment:
      - ENABLE_IPV6=true
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
  
  redis:
    image: redis:3.0-alpine
  cache:
    image: memcached:alpine
